---
# tasks file for deploy
- block: # Create dirs
    
    - name: "Create dir for app"
      file:
        path: "/home/vklymov/{{ item.dir }}"
        state: directory
      loop:
        - { dir: petclinic }
    
    - name: "Create pet_home, mysql_home, nginx_home, dockercompose dirs"
      file:
        path: "{{ item.path }}"
        state: "{{ item.state }}"
        mode: "{{ item.mode }}"
      loop:
        - { path: "/home/vklymov/petclinic/pet_home", state: "directory", mode: "0777" }
        - { path: "/home/vklymov/petclinic/mysql_home", state: "directory", mode: "0777" }
        - { path: "/home/vklymov/petclinic/pet_home", state: "directory", mode: "0755" }


- block: # Copy files
    
    - name: "Copy docker compose and env files"
      copy:
        src: "{{ item.path_to_file }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      with_items:
        - { path_to_file: ../files/petclinic-docker-compose.yaml, dest: /home/vklymov/petclinic/docker_compose, mode: preserve }
        - { path_to_file: ../files/mysql.env, dest: /home/vklymov/petclinic/docker_compose, mode: preserve  }
        - { path_to_file: ../files/pet.env, dest: /home/vklymov/petclinic/docker_compose, mode: preserve  }
        - { path_to_file: ../files/nginx.env, dest: /home/vklymov/petclinic/docker_compose, mode: preserve  }

    
- block: #Compose up stack

    - name: "Start pet compose"
      shell: docker-compose -f /home/vklymov/petclinic/docker_compose/petclinic-docker-compose.yaml up -d