version: "3.9"
services:
    jenkins:
        container_name: jenkins
        image: asxan/jenkins_cus:0.0.4
        restart: always 
        ports:
            - "8081:8081"
            - "8080:8080"
            - "22"
            - "465:465"
            - "443:443"
        volumes:
            - "$HOME/jenkins_nginx/jenkins_home:/var/jenkins_home"
        # env_file:
        #     -  ./jenkins.env
        # environment:
        #     - CASC_JENKINS_CONFIG=/var/jenkins_home/casc.yaml
        networks:
            - task-net
networks:
    task-net:

##