---
# tasks file for slave

- block:

  - name: "Make dir for override.conf"
    file:
      path: '/etc/systemd/system/docker.service.d'
      state: directory


  - name: "Copy daemon.json, override.conf and ssh key"
    copy:
      src:  "{{ item.source }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mood }}"
    loop:
      - { source: ../files/daemon.json, dest: /etc/docker, mood: preserve }
      - { source: ../files/override.conf, dest: /etc/systemd/system/docker.service.d, mood: preserve }
      - { source: ~/.ssh/jenkins_task_key.pub, dest: ~/.ssh, mood: preserve }


  - name: "Reload docker daemon"
    shell: systemctl daemon-reload

  - name: "Restart Docker service"
    service:
      name: docker
      state: restarted
      enabled: yes
      masked: no

  - name: "Check if java is installed" 
    command:  java -version
    register: java_check
    ignore_errors: yes

  - name: "Check if ansible is installed" 
    command:  ansible --version
    register: ansible_check
    ignore_errors: yes

  - name: "Install java"
    yum:
      name: java-11-openjdk-devel
      state: latest
    when:
      - java_check.msg.find('No such file or directory') != -1

  - name: "Install Ansible"
    yum:
      name: ansible
      state: latest
    when:
      - ansible_check.msg.find('No such file or directory') != -1