---
# tasks file for slave

  - name: Install java
    yum:
      - name: java-11-openjdk-devel
        state: latest


  - name: Install Ansible
    yum:
      - name: ansible
        state: latest


  - name: Copy ssh key 
    copy:
      src: ~/.ssh/jenkins_task_key.pub
      dest: ~/.ssh
      mode: preserve