---
# tasks file for packages

  # - name: "Check if Docker is installed"
  #   command: systemctl status docker
  #   register: docker_check
  #   ignore_errors: yes

  - block:

      # - name: "Yum upgrade all packages"
      #   yum:
      #     name: '*'
      #     state: latest
      #     update_cache: yes

      # - name: "Create group"
      #   group:
      #     name: "{{ group['name'] }}"
      #     state: "{{ group['state'] }}"
      #     gid: "{{ group['gid'] }}"

      
      # - name: "Create user"
      #   user:
      #     name: "{{ user['name'] }}"
      #     state: "{{ user['state'] }}"
      #     shell: "{{ user['shell'] }}"
      #     uid: "{{ user['uid'] }}"
      #     group: "{{ user['group'] }}"



      - name: "Enable Epel Repository"
        yum:
          name: epel-release
          state: latest
        when: ansible_facts['os_family'] == 'RedHat' and ansible_facts
          ['distribution_major_version'] == '7'


      - name: "Install git, pip, python-docker, yum-utils"
        yum:
          name: "{{ item.package }}"
          state: present
          update_cache: yes
        with_items:
          - { package: "{{ yum_packages[0] }}" }
          - { package: "{{ yum_packages[1] }}" }
          - { package: "{{ yum_packages[2] }}" }
          - { package: "{{ yum_packages[3] }}" }
          - { package: "{{ yum_packages[4] }}" }
          - { package: "{{ yum_packages[5] }}" }


      - name: install PyYAML and install certain python modules for docker
        pip:
          name: "{{ item.name }}"
          version: "{{ item.version }}"
        with_items:
          - { name: "{{ pip_packages[0] }}", version: "{{ pip_versions[0] }}" }
          - { name: "{{ pip_packages[1] }}", version: "{{ pip_versions[1] }}" }
    
    # when: docker_check.stderr.find('service could not be found') != -1