---
#tasks file for jenkins
  - block: #Block for All

    - name: "Create jenkins_nginx folder"
      file:
        path: '/home/vklymov/jenkins_nginx'
        state: directory

    - name: "Create Compose dir"
      file:
        path: "/home/vklymov/jenkins_nginx/docker_compose"
        state: directory
        mode: '0776'

    # - name: Delete compose file if exist
    #   file:
    #     path: /home/vklymov/jenkins_nginx/docker_compose/docker-compose-jenkins-nginx.yaml
    #     state: absent
    #   ignore_errors: yes

    - name: "Copy docker-compose jenkins-nginx yml file"
      copy:
        src: ../files/docker-compose-jenkins-nginx.yaml
        dest: /home/vklymov/jenkins_nginx/docker_compose
        mode: preserve


  - block:  # Block for Jenkins

    - name: "Pull image Jenkins"
      shell: docker pull asxan/jenkins_cus:0.0.4

    - name: "Create jenkins_home"
      file:
        path: '/home/vklymov/jenkins_nginx/{{ item.dir }}'
        state: directory
        mode: '0777'
      loop:
        - { dir: jenkins_home }
    
    - name: "Create casc_configs folder"
      file:
        path: '/home/vklymov/jenkins_nginx/jenkins_home/casc_configs'
        state: directory

    - name: "Copy jenkins.env jenkins yml file"
      copy:
        src: ../files/jenkins.env
        dest: /home/vklymov/jenkins_nginx/docker_compose
        mode: preserve

    - name: "Copy plugins.txt"
      copy:
        src: ../files/plugins.txt
        dest: /home/vklymov/jenkins_nginx/jenkins_home
        mode: preserve
  
    - name: "Start compose Jenkins"
      shell: docker-compose -f /home/vklymov/jenkins_nginx/docker_compose/docker-compose-jenkins-nginx.yaml up -d jenkins
      args:
        executable: /bin/bash

    - name: "Install plugins"
      shell: docker container exec jenkins /bin/bash -c "/usr/local/bin/install-plugins.sh < /var/jenkins_home/plugins.txt"

    - name: "Restart Jenkins"
      shell: docker-compose -f /home/vklymov/jenkins_nginx/docker_compose/docker-compose-jenkins-nginx.yaml restart -t 20 jenkins

    - name: "Copy casc.yaml"
      copy:
        src: ../files/casc.yaml
        dest: /home/vklymov/jenkins_nginx/jenkins_home/casc_configs
        mode: preserve
      notify: "Restart Jenkins"


  # - block:

  #   - name: "Create nginx_home"
  #     file:
  #       path: '/home/vklymov/jenkins_nginx/{{ item.dir }}'
  #       state: directory
  #       mode: '0777'
  #     loop:
  #       - { dir: nginx_home }

  #   - name: "Pull image nginx"
  #     shell: docker pull asxan/nginx_ssl:0.7

    # - name: "Copy jenkins-nexus-petclinic  conf file"
    #   copy:
    #     src: ../files/jenkins-nexus-petclinic.conf
    #     dest: /home/vklymov/jenkins_nginx/nginx_home
    #     mode: preserve

    # - name: "Start compose Nginx"
    #   shell: docker-compose -f /home/vklymov/jenkins_nginx/docker_compose/docker-compose-jenkins-nginx.yaml up -d nginx
    #   args:
    #     executable: /bin/bash
  