version: "3.9"
services:
    petclinic:
        container_name: petclinic
        image: asxan/petclinick
        restart: always
        ports:  
            - "3306"
            - "8080:8080"
        env_file:
            - ./pet.env
        networks:
            - pet-net
    mysql:
        container_name: mysql_pet
        image: mysql:5.7
        restart: always
        ports:
            - "3306:3306"
        env_file:
            - ./mysql.env
        volumes:
            - "$HOME/petclinic/mysql_home:/etc/mysql/conf.d:rw"
        networks:
            - pet-net
    nginx:
        container_name: nginx_pet
        image: asxan/nginx_pet:0.6
        restart: always
        ports:
            -   "8080"
            -   "80:80"
            -   "443:443"
            -   "3306"
        env_file:
            -   ./nginx.env
        # volumes:
        #     # -   "$HOME/petclinic/nginx_home/fullchain.pem:/fullchain.pem"
        #     # -   "$HOME/petclinic/nginx_home/privkey.pem:/privkey.pem"
        #     #-   "$HOME/petclinic/nginx_home/petclinic.conf:/etc/nginx/conf.d/petclinic.conf"
        networks:
            -   pet-net
networks:
    pet-net:
