---
# tasks file for nexus
- block:
  
  - name: "Create nexus_nginx dir"
    file:
      path: "{{ nexus_nginx[0] }}"
      state: "{{ nexus_nginx[1] }}"
      mode: "{{ nexus_nginx[2] }}"
      recurse: yes
  
  - name: "Create compose dir, nginx_home and nexus_home and nexus_api_dir dirs"
    file:
      path: "{{ item.path }}"
      state: directory
      mode: "{{ item.mode }}"
    loop:
      - { path: "{{ other_dirs_path[0] }}", mode: "{{ other_dirs_mood[0] }}" }
      - { path: "{{ other_dirs_path[1] }}", mode: "{{ other_dirs_mood[1] }}" }
      - { path: "{{ other_dirs_path[2] }}", mode: "{{ other_dirs_mood[2] }}" }
      - { path: "{{ other_dirs_path[3] }}", mode: "{{ other_dirs_mood[3] }}" }
      - { path: "{{ other_dirs_path[4] }}", mode: "{{ other_dirs_mood[4] }}" }

  
- block: 
  
  - name: "Copy files"
    copy: 
      src: "{{ item.source }}"
      dest: "{{ item.dest }}"
      mode: "{{ item.mode }}"
      owner: "{{ item.owner }}"
      group: "{{ item.group }}"
    loop:
      - { source: "{{ file1['src'] }}", dest: "{{ file1['dest'] }}" , mode: "{{ file1['mood'] }}", owner: "{{ file1['owner'] }}", group: "{{ file1['group'] }}" }
      - { source: "{{ file2['src'] }}", dest: "{{ file2['dest'] }}" , mode: "{{ file2['mood'] }}", owner: "{{ file2['owner'] }}", group: "{{ file2['group'] }}" }
      - { source: "{{ file3['src'] }}", dest: "{{ file3['dest'] }}" , mode: "{{ file3['mood'] }}", owner: "{{ file3['owner'] }}", group: "{{ file3['group'] }}" }
      - { source: "{{ file4['src'] }}", dest: "{{ file4['dest'] }}" , mode: "{{ file4['mood'] }}", owner: "{{ file4['owner'] }}", group: "{{ file4['group'] }}" }
      - { source: "{{ file5['src'] }}", dest: "{{ file5['dest'] }}" , mode: "{{ file5['mood'] }}", owner: "{{ file5['owner'] }}", group: "{{ file5['group'] }}" }
      - { source: "{{ file6['src'] }}", dest: "{{ file6['dest'] }}" , mode: "{{ file6['mood'] }}", owner: "{{ file6['owner'] }}", group: "{{ file6['group'] }}" }
      - { source: "{{ file7['src'] }}", dest: "{{ file7['dest'] }}" , mode: "{{ file7['mood'] }}", owner: "{{ file7['owner'] }}", group: "{{ file7['group'] }}" }
    become: yes

  - name: "Copy nexus api dir with all files"
    copy: 
      src: "{{ nexus_api_dir['src'] }}"
      dest: "{{ nexus_api_dir['dest'] }}"
      mode: "{{ nexus_api_dir['mood'] }}"
      owner: "{{ nexus_api_dir['owner'] }}"
      group: "{{ nexus_api_dir['group'] }}"
    become: yes

  - name: "Start compose Nexus"
    shell: "docker-compose -f $HOME/nexus_nginx/docker_compose/nexus-docker-compose.yaml up -d"
    args:
      executable: /bin/bash
  
  - name: "Sleep for 70 seconds"
    shell: "sleep 60"
    args: 
      executable: /bin/bash


  - name: "Start nexus api script"
    shell: "/home/vklymov/nexus_nginx/nexus_api_files/shell_nexus-api.sh"
    args: 
      executable: /bin/bash



  