version: "3.9"
services:
    jenkins:
        container_name: jenkins
        image: asxan/jenkins_cus:0.0.4
        ports:
            - "8081:8081"
            - "8080:8080"
            - "22:22"
            - "465:465"
            - "443:443"
        volumes:
            - "/home/asxan_devops/jenkins_nginx/jenkins_home:/var/jenkins_home"
        networks:
            - task-net
    # nginx:
    #     container_name: nginx
    #     image:
    #     ports:
    #         - "443:443"
    #         - "80:80"
    #         - "8080:8080"
    #         - "8081:8081"
    #     volumes:
    #         - "/home/asxan_devops/jenkins_nginx/:/etc/nginx/templates"
    #     environment:
    #         - NGINX_HOST=""
    #         - NGINX_PORT=80
    #     networks:
    #         - task-net
networks:
    task-net:

