---
- name: "Install docker and docker-compose in all servers"
  hosts: all
  become: yes
  gather_facts: yes

  tasks:
  # - name: "Yum upgrade all packages"
  #   yum:
  #     name: '*'
  #     state: latest
  #     update_cache: yes

  # - name: "Enable Epel Repository"
  #   yum:
  #     name: epel-release
  #     state: latest
  #   when: ansible_facts['os_family'] == 'RedHat' and ansible_facts
  #     ['distribution_major_version'] == '7'

  # - name: "Install git"
  #   yum:
  #     name: git
  #     state: present
  #     update_cache: yes

  # - name: "Install pip"
  #   yum: 
  #     name: python-pip
  #     state: present

  # - name: install certain python modules for docker
  #   pip:
  #     name: "{{ item.name }}"
  #     version: "{{ item.version }}"
  #   with_items:
  #   - { name: docker-py, version: 1.10.6 }

  # - name: install PyYAML
  #   pip:
  #     name: "{{ item.name }}"
  #     version: "{{ item.version }}"
  #   with_items:
  #   - { name: PyYAML, version: 5.4.1 }

  # - name: "Install python-docker"
  #   yum:
  #     name: python-docker
  #     state: present

  - name: "Install docker compose python"
    pip:
      name: "{{ item.name }}"
      version: "{{ item.version }}"
    with_items:
    - { name: docker-compose, version: 1.29.2 }