---
- name: "Install packages, docker and docker-compose in all servers" #/usr/local/src
  hosts: all
  become: yes
  gather_facts: yes
  roles:
    - packages
    - docker_install
  tags:
    - soft

- name: "Provision Jenkins"
  hosts: jenkins_nginx
  gather_facts: yes
  roles:
    - jenkins_nginx
  tags:
    - jenkins_nginx

- name: "Provision slave"
  hosts: slave_server
  become: yes
  gather_facts: yes
  roles:
    - slave
  tags:
    - slave

- name: "Provision nexus"
  hosts: nexus_server
  gather_facts: yes
  roles:
    - nexus
  tags:
    - nexus

- name: "Provision deploy instance"
  hosts: prod_server
  gather_facts: yes
  roles:
    - deploy
  tags:
    - deploy
