---
# - name: "Install packages, docker and docker-compose in all servers"
#   hosts: all
#   become: yes
#   gather_facts: yes

#   roles:
#     - packages
#     - docker_install

- name: "Provision Jenkins"
  hosts: jenkins_nginx
  gather_facts: yes

  roles:
    - jenkins_nginx

# - name: "Provision slave"
#   hosts: slave_server
#   become: yes
#   gather_facts: yes

#   roles:
#     - slave

# - name: "Provision nexus"
#   hosts: nexus_server
#   gather_facts: yes

#   roles:
#     - nexus

# - name: "Provision deploy instance"
#   hosts: prod_server
#   gather_facts: yes

#   roles:
#     - deploy
