---
# tasks file for jenkins

  # - name: "Set env jenkins admin  id"
  #   shell: echo "export JENKINS_A_ID=${JENKINS_ID}" >> ~/.bash_profile

  # - name: "Set env jenkins admin password"
  #   shell: echo "export JENKINS_PASSWORD=${JENKINS_PASSWORD}" >> ~/.bash_profile

  # - name: "Source .bash_profile"
  #   shell: source ~/.bash_profile

  - name: "Pull image"
    shell: docker pull asxan/jenkins_cus:0.0.4

  - name: "Create jenkins_nginx folder"
    file:
      path: '/home/vklymov/jenkins_nginx'
      state: directory

  - name: "Create jenkins_home & nginx_home"
    file:
      path: '/home/vklymov/jenkins_nginx/{{ item.dir }}'
      state: directory
      mode: '0777'
    loop:
      - { dir: jenkins_home }
      - { dir: nginx_home }

  - name: "Create Compose dir"
    file:
      path: "/home/vklymov/jenkins_nginx/docker_compose"
      state: directory
      mode: '0776'

  - name: Delete compose file if exist
    file:
      path: /home/vklymov/jenkins_nginx/docker_compose/docker-compose-jenkins.yaml
      state: absent
    ignore_errors: yes

  - name: "Copy docker-compose jenkins_nginx yml file"
    copy:
      src: ../files/docker-compose-jenkins.yaml
      dest: /home/vklymov/jenkins_nginx/docker_compose
      mode: preserve

  - name: "Copy docker-compose jenkins_nginx yml file"
    copy:
      src: ../files/jenkins.env
      dest: /home/vklymov/jenkins_nginx/docker_compose
      mode: preserve

  - name: "Copy plugins.txt"
    copy:
      src: ../files/plugins.txt
      dest: /home/vklymov/jenkins_nginx/jenkins_home
      mode: preserve
    notify: "Install plugins"

  # - name: "Copy casc.yaml"
  #   copy:
  #     src: ../file/casc.yaml
  #     dest: /home/vklymov/jenkins_nginx/jenkins_home
  #     mode: preserve
  #   notify: "Restart Jenkins"
  
  - name: "Start compose"
    shell: docker-compose -f /home/vklymov/jenkins_nginx/docker_compose/docker-compose-jenkins.yaml up -d
    args:
      executable: /bin/bash